#!/bin/bash
set -eo pipefail

# Build release APK for UniWhere Android
# Handles: Node 20 via nvm, Android SDK path, expo prebuild, ProGuard rules, Gradle
#
# Tunables (override via env):
#   METRO_MAX_WORKERS=2   Metro transformer processes. The JS bundle step runs while
#                         the Gradle JVM is resident; too many workers pushes a small
#                         machine into swap and the build appears to hang forever at
#                         `:app:createBundleReleaseJsAndAssets`.
#   GRADLE_XMX=1536m      Heap for the Gradle JVM. Lower it to leave room for Metro.
#   SKIP_PREBUILD=1       Reuse the existing android/ dir instead of regenerating it.
#                         Much faster to iterate; use a full run for real releases.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
NODE_20="${NODE_20:-/home/worker-node-4/.nvm/versions/node/v20.20.2/bin/node}"
ANDROID_SDK="${ANDROID_SDK:-/home/worker-node-4/Android/Sdk}"
NODE_WRAPPER="$HOME/bin/node"

export METRO_MAX_WORKERS="${METRO_MAX_WORKERS:-2}"
GRADLE_XMX="${GRADLE_XMX:-1536m}"

cd "$PROJECT_DIR"

# 1. Activate Node 20
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use 20

# Ensure ~/bin/node wrapper points to Node 20 (Gradle uses system PATH)
mkdir -p "$HOME/bin"
cat > "$NODE_WRAPPER" <<EOF
#!/bin/bash
exec $NODE_20 "\$@"
EOF
chmod +x "$NODE_WRAPPER"
export PATH="$HOME/bin:$PATH"
export ANDROID_HOME="$ANDROID_SDK"

echo "Using node:        $(node --version)"
echo "ANDROID_HOME:      $ANDROID_HOME"
echo "Metro workers:     $METRO_MAX_WORKERS"
echo "Gradle heap:       $GRADLE_XMX"
command -v free >/dev/null && echo "Memory:            $(free -h | awk '/^Mem:/ {print $7" available of "$2}')"

# 2. Prebuild (regenerate android/ native project)
if [ -n "$SKIP_PREBUILD" ]; then
  if [ ! -d android ]; then
    echo "SKIP_PREBUILD set but android/ does not exist — run once without it." >&2
    exit 1
  fi
  echo "Skipping prebuild, reusing existing android/"
else
  npx expo prebuild --platform android --clean
fi

# 3. Restore local.properties (Gradle needs NODE_BINARY for subprocesses)
echo "NODE_BINARY=$NODE_20" > android/local.properties

# 4. Restore ProGuard rules (expo.modules.* classes must not be stripped by R8).
#    Guarded so a SKIP_PREBUILD run doesn't append the block a second time.
if ! grep -q 'uniwhere:expo-modules-keep' android/app/proguard-rules.pro; then
  cat >> android/app/proguard-rules.pro <<'EOF'

# uniwhere:expo-modules-keep
# expo-modules-core — R8 strips internal Kotlin classes used at runtime via
# reflection inside expo module definitions (TypeDescriptor, etc.)
-keep class expo.modules.** { *; }
-keep interface expo.modules.** { *; }
-keepattributes *Annotation*, Signature, RuntimeVisibleAnnotations, EnclosingMethod, InnerClasses
EOF
fi

# 5. Cap the Gradle heap. android/ is gitignored and regenerated by prebuild, so this
#    has to be reapplied on every run rather than committed.
sed -i -E "s/^org\.gradle\.jvmargs=.*/org.gradle.jvmargs=-Xmx${GRADLE_XMX} -XX:MaxMetaspaceSize=512m/" \
  android/gradle.properties

# 6. Bundle the JS up front, outside Gradle.
#    Gradle swallows Metro's output, so a stall inside :app:createBundleReleaseJsAndAssets
#    is invisible — the progress bar sits at 92% either way. Running it here first means
#    a stall is visible and attributable, and Gradle's own bundle step then hits a warm
#    Metro cache. This is a cache warm-up, not a replacement: Gradle still bundles.
echo ""
echo "→ Warming the Metro bundle (this is the step that stalls; watch the module count)"
npx expo export:embed \
  --platform android \
  --dev false \
  --entry-file node_modules/expo-router/entry.js \
  --bundle-output "$(mktemp -d)/index.android.bundle" \
  --assets-dest "$(mktemp -d)"

# 7. Build release APK
echo ""
echo "→ Gradle assembleRelease"
cd android
./gradlew assembleRelease --no-daemon --console=plain

APK_PATH="$PROJECT_DIR/android/app/build/outputs/apk/release/app-release.apk"
echo ""
echo "✓ Build complete: $APK_PATH"
echo "  Size: $(du -h "$APK_PATH" | cut -f1)"
echo ""
echo "Install with:"
echo "  adb install -r $APK_PATH"
